language: r
r_packages:
 - ggplot2
 - grid
 - gridExtra
 - methods
 - scales
 - survival
 - stats
 - rmarkdown
 - knitr
 - devtools
 - magrittr
 - survMisc
 - flexsurv
bioc_packages:
 - RTCGA.clinical
sudo: required
